
/* Autogenerated file, do not edit! */

/* eslint-disable */

import { Noir, InputMap, CompiledCircuit, ForeignCallHandler } from "@noir-lang/noir_js"

export { ForeignCallHandler } from "@noir-lang/noir_js"



export type mainInputType = {
  password: string;
}

export const main_circuit: CompiledCircuit = {"abi":{"parameters":[{"name":"password","type":{"kind":"string","length":8},"visibility":"private"}],"return_type":null,"error_types":{}},"bytecode":"H4sIAAAAAAAA/7WTSw7DIAxEQ3/kODaGYO96ldDA/Y/QWs2iajeVYj8JeWc9DZ4wvYmvN0+/hH3e9wnHwM9dBEvOvaaOhCskaVwgl7YwMhYuW2KizpmrNKkgmKnjKEJ9KFw9PYOZpzw8PU92eQ5Pz7NdnsnT82LnSZ6eVzPPFTw9b3b36dqjaOe56Y75y1V7qh3Q+9K/01zi9AdPMx5GVqEFAAA="};

export async function main(password: string, foreignCallHandler?: ForeignCallHandler): Promise<null> {
  const program = new Noir(main_circuit);
  const args: InputMap = { password };
  const { returnValue } = await program.execute(args, foreignCallHandler);
  return returnValue as null;
}
